package exception;

public enum ErrorCode {
    MISSING_REQUIRED_ARGUMENTS,
    INVALID_ARGUMENT,
    UNKNOWN_INTERFACE_TYPE,
    UNKNOWN_DATA_PARSER_TYPE,
    UNKNOWN_DATA_READER_TYPE,
    FILE_READ_EXCEPTION,
    NOT_IMPLEMENTED,
    UNKNOWN_DATA_PROCESSOR;
}
